# Script mode: assembles the UWP package layout (a "loose" app that can be registered or packed).
#
# Required: EXE_DIR, LAYOUT_DIR, RES_DIR, MANIFEST, ASSETS_DIR, ARGS_FILE, CRT_DIRS (|-separated)
# Optional: ISO (disc image to embed as disc/game.iso), BUNDLED_MODS_DIR (.dusk mods to ship in mods/),
#           PIPELINE_CACHE (initial_pipeline_cache.db seeding the pipeline cache)
foreach (_var EXE_DIR LAYOUT_DIR RES_DIR MANIFEST ASSETS_DIR ARGS_FILE CRT_DIRS)
  if (NOT DEFINED ${_var})
    message(FATAL_ERROR "UWPStageLayout: ${_var} is required")
  endif ()
endforeach ()

file(MAKE_DIRECTORY "${LAYOUT_DIR}")

# Executable and the DLLs next to it (Dawn, DXC, nod, ...)
file(GLOB _binaries "${EXE_DIR}/dusklight.exe" "${EXE_DIR}/*.dll")
# The C/C++ runtime is deployed app-local, using the OneCore build that works on all device families.
string(REPLACE "|" ";" CRT_DIRS "${CRT_DIRS}")
foreach (_crt_dir IN LISTS CRT_DIRS)
  file(GLOB _crt_dlls "${_crt_dir}/*.dll")
  list(APPEND _binaries ${_crt_dlls})
endforeach ()
file(COPY ${_binaries} DESTINATION "${LAYOUT_DIR}")

file(COPY "${RES_DIR}" DESTINATION "${LAYOUT_DIR}")
file(COPY "${ASSETS_DIR}/" DESTINATION "${LAYOUT_DIR}/Assets")
file(COPY_FILE "${MANIFEST}" "${LAYOUT_DIR}/AppxManifest.xml" ONLY_IF_DIFFERENT)
file(COPY_FILE "${ARGS_FILE}" "${LAYOUT_DIR}/aurora-args.txt" ONLY_IF_DIFFERENT)

# Bundled mods, found by the mod loader in mods/ next to the executable
set(_mods_dest "${LAYOUT_DIR}/mods")
set(_bundled_mods)
if (BUNDLED_MODS_DIR)
  file(GLOB _bundled_mods "${BUNDLED_MODS_DIR}/*.dusk")
endif ()
file(GLOB _staged_mods "${_mods_dest}/*.dusk")
foreach (_staged IN LISTS _staged_mods)
  get_filename_component(_name "${_staged}" NAME)
  if (NOT EXISTS "${BUNDLED_MODS_DIR}/${_name}")
    file(REMOVE "${_staged}")
  endif ()
endforeach ()
if (_bundled_mods)
  file(COPY ${_bundled_mods} DESTINATION "${_mods_dest}")
endif ()

# aurora opens the seed relative to the working directory, which is the package root
set(_pipeline_cache_dest "${LAYOUT_DIR}/initial_pipeline_cache.db")
if (PIPELINE_CACHE)
  if (NOT EXISTS "${PIPELINE_CACHE}")
    message(FATAL_ERROR "Initial pipeline cache does not exist: ${PIPELINE_CACHE}")
  endif ()
  file(COPY_FILE "${PIPELINE_CACHE}" "${_pipeline_cache_dest}" ONLY_IF_DIFFERENT)
else ()
  file(REMOVE "${_pipeline_cache_dest}")
endif ()

set(_iso_dest "${LAYOUT_DIR}/disc/game.iso")
if (ISO)
  if (NOT EXISTS "${ISO}")
    message(FATAL_ERROR "Disc image to embed does not exist: ${ISO}")
  endif ()
  set(_up_to_date FALSE)
  if (EXISTS "${_iso_dest}")
    file(SIZE "${ISO}" _src_size)
    file(SIZE "${_iso_dest}" _dest_size)
    file(TIMESTAMP "${ISO}" _src_time "%Y%m%d%H%M%S" UTC)
    file(TIMESTAMP "${_iso_dest}" _dest_time "%Y%m%d%H%M%S" UTC)
    if (_src_size EQUAL _dest_size AND _src_time STREQUAL _dest_time)
      set(_up_to_date TRUE)
    endif ()
  endif ()
  if (NOT _up_to_date)
    file(REMOVE "${_iso_dest}")
    file(MAKE_DIRECTORY "${LAYOUT_DIR}/disc")
    # A hard link avoids duplicating the image when the build is on the same volume.
    file(CREATE_LINK "${ISO}" "${_iso_dest}" RESULT _link_result COPY_ON_ERROR)
    if (NOT _link_result EQUAL 0)
      message(FATAL_ERROR "Failed to add the disc image to the layout: ${_link_result}")
    endif ()
    message(STATUS "Embedded disc image ${ISO}")
  endif ()
else ()
  file(REMOVE_RECURSE "${LAYOUT_DIR}/disc")
endif ()
